---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-jul15-8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-jul15-8 
  name: test-jul15-8
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi